### POST create user
POST {{host}}:{{port}}/api/v1/authenticate/register
Content-Type: application/json

{
  "username" : "first@test.com",
  "password" : "Test$12345",
  "role": "USER"
}

### POST login user
POST {{host}}:{{port}}/api/v1/authenticate/login
Content-Type: application/json

{
  "username" : "first@test.com",
  "password" : "Test$12345"
}

> {% client.global.set("authToken", response.body.token); %}

### POST logout
POST {{host}}:{{port}}/api/v1/authenticate/logout
Content-Type: application/json
Authorization: Bearer {{authToken}}

